#C
[language-server.clangd]
command = "clangd"

[[language]]
name = 'c'
indent = { tab-width = 4, unit = " " }
formatter = { command = 'clang-format', args = ['--style=Chromium'] }
auto-format = true

#RUST
[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "rust"
language-servers = ["rust-analyzer" ]
formatter = { command = "rustfmt" }
auto-format = true
indent = { tab-width = 4, unit = "t" }

#PYTHON
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = { command = "black", args = ["--line-length", "88", "--quiet", "-"] }
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

#TS
[language-server.typescript-language-server]
command = "typescript-language-server"

[[language]]
name = 'typescript'
formatter = { command = 'prettier', args =  ["--parser", "typescript"] }
auto-format = true

# [language.formatter]
# command = "black"
# args = ["--line-length", "88", "--quiet", "-"]
